default: &default
  adapter: postgresql
  encoding: unicode

  pool: 5

development:
  <<: *default
  database: TripleB_development

test:
  <<: *default
  database: TripleB_test

production:
  <<: *default
  database: TripleB_production
  username: TripleB
  password: <%= ENV['TRIPLEB_DATABASE_PASSWORD'] %>
